// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import { clearSupabaseTokenValidation, getSupabaseAccessToken } from "./session-token";

function isUnauthorized(error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  return /\bUnauthorized\b/i.test(message);
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = await getSupabaseAccessToken();
    try {
      return await next({
        headers: { Authorization: `Bearer ${token}` },
      });
    } catch (error) {
      if (isUnauthorized(error)) {
        clearSupabaseTokenValidation();
        const { error: sessionError } = await supabase.auth.getUser();
        if (sessionError) {
          await supabase.auth.signOut({ scope: "local" });
          if (typeof window !== "undefined" && window.location.pathname !== "/auth") {
            window.location.assign("/auth");
          }
        }
      }
      throw error;
    }
  },
);
